.\" $RCSId: xc/programs/Xserver/hw/kdrive/fbdev/Xfbdev.man,v 1.4 2001/01/27 18:20:40 dawes Exp $
.\"
.TH Xfbdev 1 __vendorversion__
.SH NAME
Xfbdev \- Linux framebuffer device tiny X server
.SH SYNOPSIS
.B Xfbdev
.RI [ :display ]
.RI [ option ...]
.SH DESCRIPTION
.B Xfbdev
is a generic X server for Linux.
.B Xfbdev
doesn't know about any particular hardware, and uses the framebuffer
provided by the Linux framebuffer device.
.SH OPTIONS
.B Xfbdev
accepts the common options of the Xkdrive family of servers.  Please
see Xkdrive(@appmansuffix@).

.B Xfbdev
also accepts the following additional options:
.TP 8
.B -fb "</dev/fbxx>"
sets the framebuffer device path the X server will use.
.TP 8
.B -dri "[string]"
enables DRI3 support for the X server.

If
.B string
is a card node (/dev/dri/cardxx), or a render node (/dev/dri/renderDxxx),
then that device node will be used by glamor for DRI3 support.

If
.B string
is either auto or not passed at all, then glamor will
try to pick a dri card node suitable for direct rendering.
.TP 8
.B -drm-master
tells the X server to enable master permissions on the dri fd it uses
(if DRI3 is enabled).
.TP 8
.B -partial-dri
tells the X server that it is allowed to initialize DRI3 partially,
if full DRI3 initialization isn't possible
(if DRI3 is enabled).
.TP 8
.B -noshadow
disables the ShadowFB layer on supported hw, may slightly increase performance.
May also lead to flickering.
.TP 8
.B -noaccel
disables hw acceleration (similar to -dumb, but only for a single screen).
.TP 8
.B -glamor
force enables glamor render acceleration (even on top of sw renderers like softpipe/llvmpipe).
.TP 8
.B -gbm
allows glamor to use libgbm (it is only used for matching EGLDeviceEXT's to dri fd's).
.TP 8
.B -noglamor
force disables glamor render acceleration.
Also disables DRI3 and X-Video support. GLX is still enabled.
.TP 8
.B -glvendor "<library>"
tells the X server what gl vendor library to use.
Particularly useful on multi-card systems.
.TP 8
.B -force-gl
tells the X server to only use desktop OpenGL contexts.
.TP 8
.B -force-es
tells the X server to only use embedded GLES contexts.
.TP 8
.B -noxv
disables X-Video support.

.SH KEYBOARD
.B Xfbdev
supports the common special key combinations of the Xkdrive family of servers.  Please
see Xkdrive(@appmansuffix@).
.B Xfbdev
also accepts the following additional special key combinations:
.TP 8
.B Ctrl+Alt+F1...F12
For systems with virtual terminal support, these keystroke
combinations are used to switch to virtual terminals 1 through 12,
respectively.

.SH SEE ALSO
X(@miscmansuffix@), Xserver(@appmansuffix@), Xkdrive(@appmansuffix@), xdm(@appmansuffix@), xinit(@appmansuffix@).
.SH AUTHORS
The
.B Xfbdev
server was written by Keith Packard.

HW acceleration support was later added by stefan11111.
