name: ubuntu package install
description: install required packages and cache apt downloads
runs:
    using: "composite"
    steps:
        - name: root suid tar for apt caching
          run:  sudo chmod u+s /bin/tar
          shell: bash

        - name: apt cache pull
          uses: actions/cache/restore@v5
          with:
            fail-on-cache-miss: true
            path: /var/cache/apt
            key:  ${{ runner.os }}-apt-cache-v4

        - name: pkg install
          run:  sudo .github/scripts/ubuntu/install-pkg.sh
          shell: bash
